# Generated by Django 2.2.13 on 2020-11-12 18:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20201112_1628"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
