# Generated by Django 2.2.13 on 2020-11-12 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201112_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
