# Generated by Django 2.2.13 on 2020-10-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_auto_20201010_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
