# Generated by Django 2.2.13 on 2020-09-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20200223_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('[deleted]'), to='feed.Post'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
