# Generated by Django 2.2.13 on 2020-11-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0006_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="description",
        ),
    ]
