# Generated by Django 2.2.13 on 2020-11-02 18:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0007_remove_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
