# Generated by Django 3.1.4 on 2020-12-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0011_auto_20201118_1712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
    ]
