# Generated by Django 3.1.4 on 2021-01-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0012_auto_20201221_1429"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="header_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
